---
site_name: terraform-azurerm-virtual-network

repo_name: padok-team/terraform-azurerm-virtual-network
repo_url: https://github.com/padok-team/terraform-azurerm-virtual-network

plugins:
  - techdocs-core
